export const RECEIVE_ARTICLES = "RECEIVE_ARTICLES";





export const RECEIVE_ENTITIES = "RECEIVE_ENTITIES";
export const RECEIVE_ARTICLE_ENTITIES = "RECEIVE_ARTICLE_ENTITIES";


export const RECEIVE_RESULTS = "RECEIVE_RESULTS";
export const RECEIVE_COMMENTS = "RECEIVE_COMMENTS";
